version: "3"

services:
  goyav:
    image: ${REGISTRY}/${GOYAV_IMAGE}:${GOYAV_TAG}
    container_name: goyav
    environment:
      - GOYAV_DEBUG_MODE=${GOYAV_DEBUG_MODE:-false}
      - GOYAV_HOST=${GOYAV_HOST:-0.0.0.0}
      - GOYAV_PORT=${GOYAV_PORT:-80}
      - GOYAV_MAX_UPLOAD_SIZE=${GOYAV_MAX_UPLOAD_SIZE:-1}
      - GOYAV_UPLOAD_TIMEOUT=${GOYAV_UPLOAD_TIMEOUT:-10}

      - GOYAV_VERSION=${GOYAV_VERSION:-1.0}
      - GOYAV_INFORMATION

      - GOYAV_MINIO_HOST
      - GOYAV_MINIO_PORT=${GOYAV_MINIO_PORT:-9000}
      - GOYAV_MINIO_ACCESS_KEY
      - GOYAV_MINIO_SECRET_KEY
      - GOYAV_MINIO_BUCKET_NAME
      - GOYAV_MINIO_USE_SSL=${GOYAV_MINIO_USE_SSL:-false}

      - GOYAV_POSTGRES_HOST
      - GOYAV_POSTGRES_PORT=${GOYAV_POSTGRES_PORT:-5432}
      - GOYAV_POSTGRES_USER
      - GOYAV_POSTGRES_USER_PASSWORD
      - GOYAV_POSTGRES_DB
      - GOYAV_POSTGRES_SCHEMA

      - GOYAV_CLAMAV_HOST
      - GOYAV_CLAMAV_PORT=${GOYAV_CLAMAV_PORT:-3310}
      - GOYAV_CLAMAV_TIMEOUT
    ports:
      - ${PORT}:${GOYAV_PORT}
    restart: always
