version: "3"

services:
  minio:
    image: quay.io/minio/minio
    restart: always
    expose:
      - 9000
      - 9001
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    volumes:
      - /tmp/minio:/data 
    command: server /data --console-address ":9001"
    networks:
       - goyav_network

  clamav:
    image: clamav/clamav:1.2
    restart: always
    expose:
      - 3310
      - 7357
    volumes:
      - clamdb:/var/lib/clamav
    networks:
       - goyav_network

  postgres:
    image: postgres:16.1-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
      - ../../resources/sql/:/docker-entrypoint-initdb.d
    networks:
       - goyav_network
    
volumes:
  clamdb:
  postgres:

networks:
  goyav_network:
    driver: bridge
